apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
  namespace: marketplace
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/marketplace_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: marketplace_user
  SPRING_JPA_HIBERNATE_DDL_AUTO: update