apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: marketplace
type: Opaque
stringData:
  MYSQL_PASSWORD: marketplace_pass
  MYSQL_ROOT_PASSWORD: root_pass
  SPRING_DATASOURCE_PASSWORD: marketplace_pass